Controllers/ACUITY_EVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using acuity_tooll.Models;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Validation;
using EntityState = System.Data.Entity.EntityState;
using PagedList;
using PagedList.Mvc;
namespace acuity_tooll.Controllers
{
    public class ACUITY_EVController : Controller
    {
        private Entities db = new Entities();

        // GET: ACUITY_EV
        private const int pageSize = 500;
        public ActionResult acuitylist(int? page, string search)
        {
            int pageNumber = (page ?? 1);
            List<ACUITY_DETAIL> DL = new List<ACUITY_DETAIL>();
            ViewBag.MASTER_ID = new SelectList(db.ACUITY_MASTER, "ID", "TITLE");
            ViewBag.DET_ID = new SelectList(db.ACUITY_DETAIL, "ID", "SUB_TITLE");
            ViewBag.MasterList = db.ACUITY_MASTER.ToList();
            ViewBag.DetailList = db.ACUITY_DETAIL.ToList();
            ACUITY_EV eV = new ACUITY_EV();
            List<ACUITY_EV> evList = db.ACUITY_EV.Where(x=>x.ACUITY_TOOL.STATUS=="I").OrderByDescending(x=>x.ADD_DATE).Where(x => x.ACUITY_TOOL.WARD_CODE.Contains(search.ToUpper()) || x.ACUITY_TOOL.P_NAME.Contains(search.ToUpper()) ||x.NURSE_NAME.Contains(search) || search == null).ToList();
            return View(evList.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index(decimal id)
        {
            List<ACUITY_DETAIL> DL = new List<ACUITY_DETAIL>();
            ViewBag.MASTER_ID = new SelectList(db.ACUITY_MASTER, "ID", "TITLE");
            ViewBag.DET_ID = new SelectList(db.ACUITY_DETAIL, "ID", "SUB_TITLE");
            ViewBag.MasterList = db.ACUITY_MASTER.ToList();
            ViewBag.DetailList = db.ACUITY_DETAIL.ToList();
            ACUITY_EV eV = new ACUITY_EV();
            var aCUITY_EV = db.ACUITY_TOOL.Where(e => e.ID_ACUITY == id).Include(e => e.ACUITY_EV.Select(ev => ev.ACUITY_DETAIL)).Include(e => e.ACUITY_EV.Select(ev => ev.ACUITY_MASTER)).FirstOrDefault();
            return View(aCUITY_EV);
        }

        // GET: ACUITY_EV/Details/5
        public ActionResult Details(decimal? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACUITY_EV aCUITY_EV = db.ACUITY_EV.Where(X => X.AC_ID == id).Include(a=>a.ACUITY_DETAIL).Include(e=>e.ACUITY_MASTER).FirstOrDefault();
            List<ACUITY_EV> AV = db.ACUITY_EV.Where(X => X.AC_ID == id).Include(a => a.ACUITY_DETAIL).Include(e => e.ACUITY_MASTER).ToList(); 

            if (aCUITY_EV == null)
            {
                return HttpNotFound();
            }
            ViewBag.SCORE = AV.Sum(e => e.ACUITY_DETAIL.VALUE);
            return View(aCUITY_EV);
        }

        // GET: ACUITY_EV/Create
        public ActionResult Create(decimal? id = null)
        {
            if (Session["USER_ID"] != null)
            {
                ViewBag.DET_ID = new SelectList(db.ACUITY_DETAIL, "ID", "SUB_TITLE");
                ViewBag.sv = new SelectList(db.ACUITY_DETAIL, "ID", "VALUE");
                ViewBag.MASTER_ID = new SelectList(db.ACUITY_MASTER, "ID", "TITLE");
                ViewBag.USER_ID = new SelectList(db.USER_PROFILE, "USER_ID", "USER_NAME");
                ViewBag.MRN = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "MRN", id);
                ViewBag.AC_ID = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ID_ACUITY", id);
                ViewBag.P_NAME = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "P_NAME", id);
                ViewBag.ROOM = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ROOM", id);
                List<SelectListItem> SHIFTL = new List<SelectListItem>() { new SelectListItem { Text = "AM", Value = "AM" }, new SelectListItem { Text = "PM", Value = "PM" } };
                ViewBag.SHIFT = SHIFTL;
                ViewBag.MasterList = db.ACUITY_MASTER.ToList();
                ViewBag.DetailList = db.ACUITY_DETAIL.ToList();
                List<ACUITY_EV> m = db.ACUITY_EV.Where(x => x.AC_ID == id).ToList();
            

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AC_ID,MASTER_ID,DET_ID,SHIFT,ADD_DATE,SCORE,NURSE_NAME,REVIEW,REVIEWER_NAME,UPDATE_DATE,USER_ID")] ACUITY_EV aCUITY_EV, List<ACUITY_EV> details)
        {
            decimal sa= Convert.ToInt32(Session["USER_ID"]);
            try
            {
                    foreach (var detail in details)
                    {
                        detail.AC_ID = aCUITY_EV.AC_ID;
                        detail.SHIFT = aCUITY_EV.SHIFT;
                        detail.USER_ID = sa;
                        detail.REVIEW = aCUITY_EV.REVIEW;
                        detail.SHIFT = aCUITY_EV.SHIFT;
                        detail.NURSE_NAME = aCUITY_EV.NURSE_NAME;
                        detail.ADD_DATE = System.DateTime.Now.Date;
                        detail.TOTAL = aCUITY_EV.TOTAL;
                        detail.SCORE = aCUITY_EV.SCORE;
                    }
               
                ModelState.Clear();
                TryValidateModel(details);

                if (ModelState.IsValid)
                {  
                    db.ACUITY_EV.AddRange(details);
                    db.SaveChanges();
                    return RedirectToAction("acuitylist");
                }
                ModelState.Clear();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            List<SelectListItem> SHIFTL = new List<SelectListItem>(){new SelectListItem{ Text="AM", Value = "AM" },new SelectListItem{ Text="PM", Value = "PM" }};
            ViewBag.DET_ID = new SelectList(db.ACUITY_DETAIL, "ID", "SUB_TITLE", aCUITY_EV.DET_ID);
            ViewBag.MASTER_ID = new SelectList(db.ACUITY_MASTER, "ID", "TITLE", aCUITY_EV.MASTER_ID);
            ViewBag.USER_ID = new SelectList(db.USER_PROFILE, "USER_ID", "USER_NAME", aCUITY_EV.USER_ID);
            ViewBag.AC_ID = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ID_ACUITY", aCUITY_EV.AC_ID);
            ViewBag.P_NAME = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "P_NAME", aCUITY_EV.AC_ID);
            ViewBag.ROOM = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ROOM", aCUITY_EV.AC_ID);
            ViewBag.SHIFT = SHIFTL;
            ViewBag.MasterList = db.ACUITY_MASTER.ToList();
            ViewBag.DetailList = db.ACUITY_DETAIL.ToList();
            return RedirectToAction("acuitylist");
        }

        public ActionResult Report(decimal? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var main = db.ACUITY_TOOL.Where(e => e.ID_ACUITY == id).Include(e => e.ACUITY_EV.Select(ev => ev.ACUITY_DETAIL)).Include(e => e.ACUITY_EV.Select(ev => ev.ACUITY_MASTER)).FirstOrDefault();

            if (main == null)
            {
                return HttpNotFound();
            }
            ViewBag.MasterList = db.ACUITY_MASTER.ToList();
            ViewBag.DetailList = db.ACUITY_DETAIL.ToList();
            return View(main);
        }
        // GET: ACUITY_EV/Edit/1803
        public ActionResult Edit(decimal? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACUITY_EV aCUITY_EV = db.ACUITY_EV.Where(X => X.AC_ID == id).FirstOrDefault();
            if (aCUITY_EV == null)
            {
                return HttpNotFound();
            }
            ViewBag.MRN = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "MRN", id);
            ViewBag.AC_ID = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ID_ACUITY", id);
            ViewBag.P_NAME = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "P_NAME", id);
            ViewBag.ROOM = new SelectList(db.ACUITY_TOOL, "ID_ACUITY", "ROOM", id);
            ViewBag.SHIFT = new List<SelectListItem>(){ new SelectListItem { Text = "AM", Value = "AM" }, new SelectListItem { Text = "PM", Value = "PM" } }.Select(r => new SelectListItem {
               Value = r.Value,
               Text = r.Text,
               Selected = r.Value == aCUITY_EV.SHIFT }).ToList();
            return View(aCUITY_EV);
        }

        // POST: ACUITY_EV/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ACUITY_EV aCUITY_EV)
        {
            if (Session["USER_ID"] != null)
            {
                List<ACUITY_EV> details = db.ACUITY_EV.Where(x=>x.AC_ID==aCUITY_EV.AC_ID).ToList();
            try
            {
                foreach (var s in details)
                {
                    s.NURSE_NAME = aCUITY_EV.NURSE_NAME;

Views/ACUITY_EV/Create.cshtml
@using acuity_tooll.Models
@model ACUITY_EV

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <br />
    <br />
    <div class="form-horizontal">
        <h4 style="color:#1C4288; font-weight:bold">Add New Acuity</h4>
        <hr />
        <div class="container shadow">
            <div class="container shadow p-3">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group" style="display: none;">
                    @Html.DropDownList("AC_ID", null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AC_ID, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.AC_ID, "MRN :", htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883; font-weight:bold" })<br />
                    <div class="col-md-10">
                        @Html.DropDownList("MRN", null, new { @class = "form-control", @style = "width:400px; border:none; background:none; padding:0", disabled = "disabled" })
                        @Html.ValidationMessageFor(model => model.AC_ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ACUITY_TOOL.P_NAME, "Petient Name :", htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883; font-weight:bold" })<br />
                    <div class="col-md-10">
                        @Html.DropDownList("P_NAME", null, new { @class = "form-control", @style = "width:400px; border:none; background:none; padding:0", @readonly = true, disabled = "disabled" })
                        @Html.ValidationMessageFor(model => model.ACUITY_TOOL.P_NAME, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ACUITY_TOOL.ROOM, "ROOM :", htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883; font-weight:bold" })
                    <div class="col-md-10">
                        @Html.DropDownList("ROOM", null, new { @class = "form-control", type = "tel", disabled = "disabled", @style = "width:400px; border:none; background:none; padding:0" })
                        @Html.ValidationMessageFor(model => model.ACUITY_TOOL.ROOM, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.SHIFT, "Shift :", htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883;width:400px; border:none;background:none; font-weight:bold" })
                    <div class="col-md-10">
                        @Html.DropDownList("SHIFT", null, htmlAttributes: new { @class = "form-control dropdown", @style = "width:500px;background:none; padding:0" })
                        @Html.ValidationMessageFor(model => model.SHIFT, "", new { @class = "text-danger" })
                    </div>
                </div>
 
                <br />
                <input type="hidden" name="MASTER_ID" value="1" />
                <input type="hidden" name="DET_ID" value="1" />


                @{

                    var counter = 0;
                    foreach (var master in (List<ACUITY_MASTER>)ViewBag.MasterList)
                    {
                        var masterDetailList = ((List<ACUITY_DETAIL>)ViewBag.DetailList).Where(e => e.MASTER_ID == master.ID).ToList();
                        var det = masterDetailList.Select(s => s.VALUE).ToList();


                        <input type="hidden" name="details[@counter].MASTER_ID" value="@master.ID" />

                        <div class="form-group">
                            <label class="control-label col-2" style="color:#00a883; font-weight:bold"> @master.TITLE : </label>
                            <div class="row-cols-2" id="V2">
                                @Html.DropDownList($"details[{counter}].DET_ID", new SelectList(masterDetailList, "ID", "SUB_TITLE", det), htmlAttributes: new { @class = "form-control dropDownId items", @id = "dropDownId", @style = "width:500px;background:none; padding:0", value = "@model => model.ACUITY_DETAIL.VALUE" })
                                @Html.ValidationMessageFor(model => model.DET_ID, "", new { @class = "text-danger" })
                                @*<div>
                            @Html.DropDownListFor(model => model.ACUITY_DETAIL.VALUE, new SelectList(det), new { @id = "vv", @class = "auto" })

                        </div>*@
                                @*@Html.DropDownListFor(model => model.ACUITY_DETAIL.VALUE, new SelectList(det, "ID", "VALUE"), htmlAttributes: new { @class = "form-control  auto" })*@
                                @*@Html.DropDownList(, new List<SelectListItem>(), "--Select--", new { @id = "vv" })*@
                            </div>
                        </div>
                        @*if (counter % 4 == 3)
                {
                    <br />
                }*@
                        counter++;
                        @*if (counter == 16)
                    { var total = det.Sum();
                <table>
                    <label>Total Score</label>
                    <br />
                    <input type="text" value="@total" style="border:none" />
                </table>*@
                        //}
                    }

                }
                <br />
                <label style="color:#00a883; font-weight:bold">Total Scoring : </label>
                <label id="LabelTotal" style="font-weight:bold"></label>

                <br />
                <label style="color:#00a883; font-weight:bold">Score : </label>
                <label id="Labelscore" style="font-weight:bold"></label><br /><br />
                @*<div style="display: none;">
                    @Html.LabelFor(model => model.SCORE, htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883; font-weight:bold" })

                    @Html.EditorFor(model => model.SCORE, new { htmlAttributes = new { @class = "form-control", @style = "width:500px;background:none; padding:0" } })

                    @Html.ValidationMessageFor(model => model.SCORE, "", new { @class = "text-danger" })
                </div>*@
                @Html.LabelFor(model => model.NURSE_NAME, "Nurse Name :", htmlAttributes: new { @class = "control-label col-md-2", style = "color:#00a883; font-weight:bold" })
                @Html.EditorFor(model => model.NURSE_NAME, new { htmlAttributes = new { @class = "form-control", @style = "width:500px;background:none; padding:0" } })
                @Html.ValidationMessageFor(model => model.NURSE_NAME, "", new { @class = "text-danger" })
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn " style="background-color:#1C4288; color:#ffffff; font-weight:bold" />
                    </div>
                </div>
                <br />
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script rel="javascript" type="text/javascript" href="js/jquery-1.11.3.min.js"></script>
<script>
    $(document).ready(function () {
        CalculateTotal();
        $('.items').change(function () { CalculateTotal(); });
    });

    function CalculateTotal() {
        var val = 0;
        
        $('.items').each(function () {
            var cv = parseFloat($(this).find('option:selected').val());
            var vv = 0;
            if (cv == 4 || cv == 8 || cv == 12 || cv == 16 || cv == 26 || cv == 30 || cv == 34 || cv == 38 || cv == 42 || cv == 46 || cv == 53 || cv ==57) { vv = 0; }
            else if (cv == 1 || cv == 5 || cv == 9 || cv == 13 || cv == 17 || cv == 20 || cv == 23 || cv == 27 || cv == 31 || cv == 35 || cv == 39 || cv == 43 || cv == 47 || cv == 50 || cv == 54 || cv ==58) { vv = 1;}
            else if (cv == 2 || cv == 6 || cv == 10 || cv == 14 || cv == 18 || cv == 21 || cv == 24 || cv == 28 || cv == 32 || cv == 36 || cv == 40 || cv == 44 || cv == 48 || cv == 51 || cv == 55 || cv ==59) { vv = 2;}
            else if (cv == 3 || cv == 7 || cv == 11 || cv == 15 || cv == 19 || cv == 22 || cv == 25 || cv == 29 || cv == 33 || cv == 37 || cv == 41 || cv == 45 || cv == 49 || cv == 52 || cv == 56 || cv ==60) { vv = 3;}
            val = val + vv ;
        });
        $('#LabelTotal').text(val);
        if (val < 17) { $('#Labelscore').text("1"); } else if (val < 24) { $('#Labelscore').text("2"); } else if (val > 24) { $('#Labelscore').text("3"); }
        val = 0;
    }
</script>

Views/ACUITY_EV/Index.cshtml
@model acuity_tooll.Models.ACUITY_TOOL
@using acuity_tooll.Models

@{
    ViewBag.Title = "Index";
}
<br /><br />
<div>
    <table class="table small">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MRN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P_NAME)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ROOM)
            </th>
            <th>
                SHIFT
            </th>
            <th>
                Ward
            </th>
            <th>
               Scoring Total
            </th>
            <th>
                Score
            </th>
            <th>
                Nurse Name
            </th>

        </tr>

        @foreach (var item in Model.ACUITY_EV.GroupBy(e => new { e.SHIFT, e.ADD_DATE ,e.NURSE_NAME}).Select(e => new { Key = e.Key, List = e.ToList() }).Select(e => new
        {
            ID = Model.ID_ACUITY,
            MRN = Model.MRN,
            NAME = Model.P_NAME,
            ROOM = Model.ROOM,
            addm = Model.ADD_DATE,
            WARD=Model.WARD_DIS,
            SHIFT = e.Key.SHIFT,
            NURSE=e.Key.NURSE_NAME,
            ADD_DATE = e.Key.ADD_DATE,
            bag_det_mas = e.List.Select(ev => new { ev.ACUITY_MASTER, ev.ACUITY_DETAIL }),
            TOTAL = e.List.Sum(ev => ev.ACUITY_DETAIL.VALUE)


        }).ToList())

        {
            <tr>
                <td style="word-break:break-all;">
                    @item.MRN
                </td>

                <td>
                    @item.NAME
                </td>
                <td>
                    @item.ROOM
                </td>
                <td>
                    @item.SHIFT
                </td>
                <td>
                    @item.WARD
                </td>
                <td>
                    @item.TOTAL
                </td>

                <td>
                    @if (item.TOTAL < 17)
                    {
                        <p> 1</p>
                    }
                    else if (item.TOTAL < 24)
                    {
                        <p>2 </p>
                    }
                    else if (item.TOTAL > 24)
                    {
                        <p> 3 </p>
                    }

                </td>
                <td>@item.NURSE</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "ACUITY_EV", new { id = item.ID }, null) |
                    @Html.ActionLink("Details", "Details", "ACUITY_EV", new { id = item.ID }, null)
                </td>
            </tr>
        }


    </table>


</div>



Views/ACUITY_EV/acuitylist.cshtml
@using acuity_tooll.Models
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ACUITY_EV>
@{
    ViewBag.Title = "acuitylist";
}
<br />
<br />
<style>

    #pager {
        padding-left: 5%
    }

        #pager p {
            margin-left: 5%;
        }
</style>
<div>
    <a href="~/Home/addacuity" style="font-weight:bold;">
        <img src="~/images/ADDD.png" /> Add Patient Acuity
    </a>
    <hr />
    @using (@Html.BeginForm("acuitylist", "ACUITY_EV", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    @Html.TextBox("search", "", new { @class = "form-control" })
                </td>
                <td>
                    <button type="submit" style=" background-image: url('../../images/search.png');background-repeat:no-repeat; width:40px;height:40px; color: #ffffff;" class=" btn " />
                </td>
            </tr>
        </table>
    }
    <br />
    <table class="table small justify-content-center" style="text-align:center">
        <tr>
            <th style="color:#1c4288; font-weight:bold">Acuity Date</th>
            <th style="color:#1c4288; font-weight:bold">
                MRN
            </th>
            <th style="color:#1c4288; font-weight:bold"> Patient Name </th>
            <th style="color:#1c4288; font-weight:bold">
                Room
            </th>
            <th style="color:#1c4288; font-weight:bold">
                SHIFT
            </th>
            <th style="color:#1c4288; font-weight:bold">
                Ward
            </th>
            <th style="color:#1c4288; font-weight:bold">
                Scoring Total
            </th>
            <th style="color:#1c4288; font-weight:bold">
                Score
            </th>
            <th style="color:#1c4288; font-weight:bold">
                Nurse
            </th>
            <th style="color:#1c4288; font-weight:bold">
                Reviewed?
            </th>


        </tr>

        @foreach (var item in Model.GroupBy(e => new { e.ACUITY_TOOL.P_NAME, e.ACUITY_TOOL.MRN, e.ACUITY_TOOL.ROOM, e.SHIFT, e.NURSE_NAME, e.ACUITY_TOOL.WARD_DIS, e.ADD_DATE, e.REVIEW, e.ACUITY_TOOL.ID_ACUITY }).Select(e => new { Key = e.Key, List = e.ToList() }).Select(e => new
        {
            ID = e.Key.ID_ACUITY,
            MRN = e.Key.MRN,
            NAME = e.Key.P_NAME,
            ROOM = e.Key.ROOM,
            addm = e.Key.ADD_DATE,
            WARD = e.Key.WARD_DIS,
            SHIFT = e.Key.SHIFT,
            rev = e.Key.REVIEW,
            NURSE = e.Key.NURSE_NAME,
            ADD_DATE = e.Key.ADD_DATE.Value,
            bag_det_mas = e.List.Select(ev => new { ev.ACUITY_MASTER, ev.ACUITY_DETAIL }),
            TOTAL = e.List.Sum(ev => ev.ACUITY_DETAIL.VALUE)


        }).ToList())

        {
            <tr>
                <td>@item.ADD_DATE.ToString(string.Format("dd/MM/yyyy"))</td>
                <td style="word-break:break-all;">
                    @item.MRN
                </td>

                <td>
                    @item.NAME
                </td>
                <td>
                    @item.ROOM
                </td>
                <td>
                    @item.SHIFT
                </td>
                <td>
                    @item.WARD
                </td>
                <td>
                    @item.TOTAL
                </td>

                <td>
                    @if (item.TOTAL < 17)
                    {
                        <p> 1</p>
                    }
                    else if (item.TOTAL < 24)
                    {
                        <p>2 </p>
                    }
                    else if (item.TOTAL > 24)
                    {
                        <p> 3 </p>
                    }

                </td>
                <td style="color:#00a883; font-weight:bold">@item.NURSE</td>
                <td>
                    @if (item.rev == "F")
                    {
                        @*<p> No </p>*@
                        <img src="~/images/ccf.png" />
                    }
                    else if (item.rev == "T")
                    {
                        @*<p>Yes</p>*@
                        <img src="~/images/checked.png" />
                    }

                </td>

                <td>
                    @Html.ActionLink("Details", "Details", "ACUITY_EV", new { id = item.ID }, null)
                    @if (Session["USER_NAME"] != null)
                    {<span>
                            | @Html.ActionLink("Edit", "Edit", "ACUITY_EV", new { id = item.ID }, null) |
                            @Html.ActionLink("Delete", "Delete", "ACUITY_EV", new { id = item.ID }, null)
                        </span>
                    }
                </td>
            </tr>
        }

<br />
    </table>
    @*@Html.PagedListPager(Model,i=>Url.Action("acuitylist","ACUITY_EV",new {i}))*@
    <div id="pager">
        <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
        @Html.PagedListPager(Model, page => Url.Action("acuitylist", "ACUITY_EV", new { page, @class = "btn btn-default" }))
    </div>

</div>
